# Generated by Django 3.2.5 on 2021-07-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0004_teacher_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coursetime', models.TextField(blank=True)),
                ('courseacademy', models.CharField(max_length=30)),
                ('credits', models.FloatField()),
                ('compulsory', models.BooleanField(default=False)),
                ('typeofcourse', models.CharField(max_length=20)),
                ('typeofelective', models.TextField(blank=True)),
                ('campus', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.teacher')),
            ],
        ),
    ]
