# Generated by Django 3.2.5 on 2021-07-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='typeofelective',
            new_name='description',
        ),
    ]
