# Generated by Django 3.2.5 on 2021-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_typeofelective_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
