# Generated by Django 3.2.5 on 2021-07-25 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(blank=True, max_length=30)),
                ('stars', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
